version: "3.4"
services:
  api:
    image: moninoeurovisio/exercise-db_api
    restart: always
    ports:
      - "1111:1111"
    links:
      - "mariadb:localhost"
    depends_on:
      - mariadb

  mariadb:
    image: moninoeurovisio/exercise-db_mariadb
    ports:
      - "3306:3306"